void clrptrren(int x,int y);
void selectren(int x,int y);
void pointren(int x,int y);
void rookren(int x,int y);
void bishopren(int x,int y);
void pawnren(int x,int y);
void knightren(int x,int y);
void queenren(int x,int y);
void kingren(int x,int y);
void emptyren(int x,int y);
void display(char* data);
void bcolor(int x,int y);
void wcolor(int x,int y);
void debugpt(int a,int b,int c,int d,char e,char f,char g,char h);
void wck();
void bck();
void cck();
void bmv();
void wmv();
